export function Name() {
  const names = [
    "Marissa Friedman",
    "Gemma Mckee",
    "Joe Khan",
    "Kayne Johns",
    "Gianluca Mccullough",
    "Joanna Skinner",
    "Mitchell Obrien",
    "Zack Ware",
    "Marion Mcgowan",
    "Lottie Cisneros",
    "Moses Mclaughlin",
    "Kendra Cohen",
    "Haydn Armstrong",
    "Meredith Hendrix",
    "Jose Hooper",
    "Casper Bonilla",
    "Alastair Sutherland",
    "Saad Barker",
    "Autumn Roach",
    "Gloria Dean",
    "Daniel Mathews",
    "Gail Koch",
    "Kiera Flynn",
    "Eliot Soto",
    "Montgomery Baird",
    "Ida Thornton",
    "Nieve Glover",
    "Rajan Blake",
    "Oakley Lowe",
    "Belle Vang",
    "Ahmed Wise",
    "Abi Miller",
    "Johnathan Glenn",
    "Nevaeh Colon",
    "Tanya Guerra",
    "Rosa Wheeler",
    "Harrison Adams",
    "Ines Rollins",
    "Aryan Hopkins",
    "Ffion Thomas",
    "Mildred Ho",
    "Kevin Rivas",
    "Alanna Peterson",
    "Kaya Waller",
    "Zara Buchanan",
    "Katelyn Robbins",
    "Raphael Jones",
    "Herbie Pollard",
    "Rowan Lawson",
    "Jane Moore",
  ];

  let posP = Math.floor(Math.random(12) * (12 - 0) + 0);
  let resultP = names[posP];

  return <div>{resultP}</div>;
}
